---
- name: "AT Computing - HashiCorp Demo - General server configuration."
  hosts: all
  become: true

  vars_files:
    - vars/general/main.yml
    - vars/hashicorp/general.yml

  pre_tasks:
    - name: Ensure the apt cache is updated before we are going to install.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      tags: pre_apt

  roles:
    - role: geerlingguy.pip
      tags: roles
    - role: geerlingguy.docker
      ignore_errors: true
      when: inventory_hostname in groups['clients']
      tags: roles
    - role: chrisvanmeer.hashicorp
      ignore_errors: true
      tags: roles

  tasks:
    - name: Install autocompletion.
      ansible.builtin.command: "{{ item[0] }} -autocomplete-install"
      become: "{{ item[1] }}"
      with_nested:
        - "{{ hashicorp_product_selection }}"
        - ["true", "false"]
      register: autoinstall_cmd
      changed_when:
        - not 'already installed' in autoinstall_cmd.stderr
      failed_when:
        - autoinstall_cmd.rc != 0
        - not 'already installed' in autoinstall_cmd.stderr

    - name: Ensure hosts file has correct entry for 127.0.1.1
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: "^127.0.1.1$"
        line: "127.0.1.1 {{ ansible_hostname }}"
      tags: hosts

    - name: Ensure dnsmasq is present.
      ansible.builtin.apt:
        name: dnsmasq
        state: present
      tags: dns

    - name: Retrieve current DNS server
      ansible.builtin.shell: "/usr/bin/resolvectl | awk '/Current DNS Server:/ {print $4}'"
      become: false
      changed_when: false
      register: current_dns_server
      tags: dns

    - name: Set the current DNS server as a fact.
      ansible.builtin.set_fact:
        dnsmasq_default_domain_server: "{{ current_dns_server.stdout_lines[0] }}"
      tags: dns

    - name: Ensure new default dnsmasq config is in place.
      ansible.builtin.template:
        src: templates/dnsmasq/dnsmasq.conf.j2
        dest: /etc/dnsmasq.conf
        backup: true
        force: true
        mode: "0644"
      notify: Restart dnsmasq
      tags: dns

    - name: Ensure Consul dnsmasq config is in place.
      ansible.builtin.template:
        src: templates/dnsmasq/dnsmasq.d/10-consul.j2
        dest: /etc/dnsmasq.d/10-consul
        force: true
        mode: "0644"
      notify: Restart dnsmasq
      tags: dns

    - name: Ensure systemd-resolved is stopped.
      ansible.builtin.service:
        name: systemd-resolved
        state: stopped
        enabled: false
      tags: dns

    # - name: Use this to revert back to the old resolv.conf file.
    #   file:
    #     src: /run/systemd/resolve/stub-resolv.conf
    #     dest: /etc/resolv.conf
    #     state: link

    - name: Ensure new resolv.conf file is present.
      ansible.builtin.template:
        src: templates/dnsmasq/resolv.conf.j2
        dest: /etc/resolv.conf
        mode: "0644"
        force: true
      tags: dns

    - name: Ensure dnsmasq is started and enabled.
      ansible.builtin.service:
        name: dnsmasq
        state: started
        enabled: true
      tags: dns

    - name: Ensure basic apt packages are installed.
      ansible.builtin.apt:
        name: "{{ basic_apt_packages }}"
        state: present
      tags: apt

    - name: Ensure .hushlogin is present in atcomputing user home dir.
      ansible.builtin.file:
        path: "/home/{{ atcomputing_user }}/.hushlogin"
        state: touch
        mode: "0644"

    - name: Ensure token directory is present.
      ansible.builtin.file:
        path: "{{ token_directory }}/"
        state: directory
        mode: 0755
      delegate_to: localhost
      become: false
      run_once: true

    - name: Ensure the correct timezone is used.
      community.general.system.timezone:
        name: "{{ timezone }}"

  handlers:
    - name: Restart dnsmasq
      ansible.builtin.service:
        name: dnsmasq
        state: restarted
