---
- name: "HashiCorp - Nomad - Jobs : Demo Jobs."
  hosts: all
  become: true

  vars_files:
    - vars/general/main.yml
    - vars/hashicorp/general.yml
    - vars/hashicorp/nomad.yml
    - vars/hashicorp/demo.yml
    - vars/hashicorp/ssl.yml

  tasks:
    - name: "HashiCorp - Nomad - Jobs : Register the Node ID from the first client for constraints demo."
      shell: "{{ nomad_binary }} node status -self -short | grep ID -m1 | awk '{print $3}'"
      changed_when: false
      register: nomad_first_client_node_id
      delegate_to: "{{ groups['clients'] | first }}"

    - name: "HashiCorp - Nomad - Jobs : Deployment."
      block:
        - name: "HashiCorp - Nomad - Jobs : Ensure job directory is present on the first server."
          become: true
          file:
            path: "{{ nomad_demo_job_remote_location }}"
            state: directory
            recurse: true

        - name: "HashiCorp - Nomad - Jobs : Ensure job directory is present on this client."
          become: true
          file:
            path: "{{ nomad_demo_job_local_location }}"
            state: directory
            mode: "0777"
          delegate_to: localhost

        - name: "HashiCorp - Nomad - Jobs : Ensure demo jobs are templated and in place."
          template:
            src: "{{ item.template }}"
            dest: "{{ item.destination }}"
            mode: "0666"
          with_items: "{{ nomad_demo_job_names }}"
          when: nomad_first_client_node_id is defined

        - name: "HashiCorp - Nomad : Retrieve job content."
          fetch:
            src: "{{ item.destination }}"
            dest: "{{ nomad_demo_job_local_location }}/"
            flat: yes
          with_items: "{{ nomad_demo_job_names }}"

        - name: "HashiCorp - Nomad : Ensure demo jobs are running."
          community.general.nomad_job:
            host: localhost
            use_ssl: false
            state: present
            content: "{{ lookup('file', item.destination) }}"
            timeout: 60
            force_start: true
          with_items: "{{ nomad_demo_job_names }}"
      when:
        - ansible_hostname in groups['servers']
      delegate_to: "{{ groups['servers'] | first }}"
      run_once: true

    - name: "HashiCorp - Nomad - CA"
      block:
        - name: "HashiCorp - Nomad - CA : Ensure that the local certs directory exists."
          file:
            path: "{{ ssl_local_ca_dir }}"
            state: directory
            mode: "0755"

        - name: "HashiCorp - Nomad - CA : Install our own self signed CA Certificate."
          copy:
            src: "{{ ssl_ca_cert }}"
            dest: "{{ ssl_local_ca_dir }}/{{ ssl_local_ca_file }}"
            mode: "0644"

        - name: "HashiCorp - Nomad - CA : Ensure CA certificates database is updated."
          command: "/usr/sbin/update-ca-certificates"
          changed_when: false

      delegate_to: localhost
      run_once: true
      tags: ca
