---
- name: "AT Computing - HashiCorp Demo - Vault Hardening"
  hosts: servers
  become: false

  vars_files:
    - vars/hashicorp/general.yml
    - vars/hashicorp/vault.yml

  tasks:
    - name: "HashiCorp - Vault - Create fact of admin password."
      ansible.builtin.set_fact:
        admin_password: "{{ lookup('file', vault_admin_local_path) }}"
      delegate_to: localhost
      run_once: true

    - name: "HashiCorp - Vault - Retrieve Initial Root Token from local file."
      ansible.builtin.shell: "awk '/Initial Root Token/ {print $4}' {{ vault_bootstrap_init_local_path }}"
      register: vault_initial_root_token
      changed_when: false
      delegate_to: localhost
      run_once: true

    - name: "HashiCorp - Vault - Revoke root token."
      block:
        - name: "HashiCorp - Vault - Revoke root token - Retrieve client token."
          ansible.builtin.uri:
            url: "{{ vault_address }}/v1/auth/userpass/login/{{ vault_admin_username }}"
            method: POST
            body_format: json
            body: '{ "password": "{{ admin_password }}" }'
            status_code:
              - 200
              - 204
            validate_certs: false
          register: vault_admin_login_response

        - name: "HashiCorp - Vault - Revoke root token - Set fact of client token."
          ansible.builtin.set_fact:
            admin_token: "{{ vault_admin_login_response.json.auth.client_token }}"

        - name: "HashiCorp - Vault - Revoke root token - Revoke."
          ansible.builtin.uri:
            url: "{{ vault_address }}/v1/auth/token/revoke"
            method: POST
            headers:
              X-Vault-Token: "{{ admin_token }}"
            body_format: json
            body: '{ "token": "{{ vault_initial_root_token.stdout }}" }'
            status_code:
              - 200
              - 204
            validate_certs: false
          register: vault_revoke_response

      tags: revoke
      delegate_to: "{{ groups['servers'] | first }}"
      run_once: true
