---
- name: Get a clean slate.
  hosts: localhost
  become: true

  vars_files:
    - vars/general/main.yml
    - vars/multipass/main.yml
    - vars/hashicorp/general.yml
    - vars/hashicorp/ssl.yml

  tasks:
    - name: LOCALHOST
      tags: localhost
      block:
        - name: Remove the comment block from the hosts file.
          ansible.builtin.blockinfile:
            backup: true
            path: /etc/hosts
            state: absent
            block: |
              # Added for the AT HashiCorp Demo - discard afterwards

        - name: Remove the instances from the hosts file.
          ansible.builtin.lineinfile:
            dest: /etc/hosts
            regexp: ".*{{ hostvars[item].ansible_host }} {{ item }}"
            state: absent
          with_items: "{{ groups.all }}"

        - name: Remove items from known hosts file based on IP.
          ansible.builtin.command: 'ssh-keygen -f "~/.ssh/known_hosts" -R "{{ hostvars[item].ansible_host }}"'
          become: false
          changed_when: true
          with_items: "{{ groups.all }}"

        - name: Remove items from known hosts file based on hostname.
          ansible.builtin.command: 'ssh-keygen -f "~/.ssh/known_hosts" -R "{{ item }}"'
          become: false
          changed_when: true
          with_items:
            - "{{ multipass_instances.clients }}"
            - "{{ multipass_instances.servers }}"

    - name: MULTIPASS
      tags: multipass
      block:
        - name: Auth against Multipass.
          ansible.builtin.command: "multipass authenticate {{ multipass_passphrase }}"
          no_log: true
          changed_when: false

        - name: Delete existing instances.
          ansible.builtin.command: "multipass delete {{ item }}"
          ignore_errors: true
          changed_when: true
          with_items:
            - "{{ multipass_instances.clients }}"
            - "{{ multipass_instances.servers }}"

        - name: Purge the multipass inventory after deletion.
          ansible.builtin.command: "multipass purge"
          changed_when: false

    - name: Remove inventory
      tags: inventory
      ansible.builtin.file:
        path: inventory
        state: absent
      delegate_to: localhost
      run_once: true

    - name: Remove tokens
      tags: tokens
      become: false
      ansible.builtin.file:
        path: "{{ token_directory }}"
        state: absent
      delegate_to: localhost
      run_once: true
